load /home/ZhangXingYi/local/maude/model-checker.maude .
load triple.maude .
load neighbor.maude .
load cube.maude .

search [1, 3] (
    (f[face(1)]: C1 C1 C5 C1 C1 C5 C1 C1 C5)
    (f[face(2)]: C2 C2 C2 C2 C2 C2 C2 C2 C2)
    (f[face(3)]: C3 C3 C3 C3 C3 C3 C1 C1 C1)
    (f[face(4)]: C4 C4 C4 C4 C4 C4 C4 C4 C4)
    (f[face(5)]: C6 C6 C6 C5 C5 C5 C5 C5 C5)
    (f[face(6)]: C3 C6 C6 C3 C6 C6 C3 C6 C6)
    ) =>* S:State such that success(S:State) .